# To install the git pre-commit hook run:
#   pre-commit install
# To update the pre-commit hooks run:
#   pre-commit install-hooks
exclude: ^(\.tox|ci|\.bumpversion\.cfg)(/|$)
default_stages: [commit, merge-commit, push]
repos:
- repo: https://github.com/jorisroovers/gitlint
  rev: v0.17.0
  hooks:
  - id: gitlint
    stages: [commit-msg]
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  - id: check-added-large-files
  - id: check-ast
  - id: check-case-conflict
  - id: check-docstring-first
  - id: check-executables-have-shebangs
  - id: check-json
  - id: check-xml
  - id: check-yaml
  - id: debug-statements
  - id: detect-private-key
  - id: double-quote-string-fixer
  - id: end-of-file-fixer
  - id: fix-byte-order-marker
  - id: mixed-line-ending
  - id: trailing-whitespace
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.2.0
  hooks:
  - id: pretty-format-ini
    args: [--autofix]
  - id: pretty-format-toml
    args: [--autofix]
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
- repo: https://github.com/PyCQA/docformatter
  rev: v1.5.0
  hooks:
  - id: docformatter
    args: [--in-place, --wrap-summaries, '95', --config, ./pyproject.toml]
- repo: https://github.com/myint/rstcheck
  rev: 3f92957
  hooks:
  - id: rstcheck
    args: [--report=warning, '--ignore-directives=automodule,testsetup']
    additional_dependencies: [sphinx]
- repo: https://github.com/PyCQA/pydocstyle
  rev: 6.1.1
  hooks:
  - id: pydocstyle
    additional_dependencies: [toml]
- repo: https://github.com/timothycrosley/isort
  rev: 5.10.1
  hooks:
  - id: isort
- repo: https://github.com/pycqa/flake8
  rev: 3.9.2
  hooks:
  - id: flake8
    args: ['--exclude=.tox,.eggs,ci/templates,build,dist']
- repo: https://github.com/asottile/pyupgrade
  rev: v2.31.0
  hooks:
  - id: pyupgrade
    args: [--py36-plus]
- repo: https://github.com/psf/black
  rev: 22.10.0
  hooks:
  - id: black
    args: [--skip-string-normalization, --line-length=79]
- repo: https://github.com/asottile/blacken-docs
  rev: v1.12.0
  hooks:
  - id: blacken-docs
    additional_dependencies: [black==21.12b0]
- repo: https://github.com/Yelp/detect-secrets
  rev: v1.1.0
  hooks:
  - id: detect-secrets
          # args: [--baseline, ci/secrets.baseline]
